// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Questionario.Data;

#nullable disable

namespace Questionario.Migrations
{
    [DbContext(typeof(QuestionarioDBContext))]
    [Migration("20241029171402_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Questionario.Models.ObraModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(144)
                        .HasColumnType("varchar(144)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(144)
                        .HasColumnType("varchar(144)");

                    b.HasKey("Id");

                    b.ToTable("Obra");
                });

            modelBuilder.Entity("Questionario.Models.VisitanteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(144)
                        .HasColumnType("varchar(144)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(144)
                        .HasColumnType("varchar(144)");

                    b.Property<int>("Questao1")
                        .HasColumnType("int");

                    b.Property<int>("Questao2")
                        .HasColumnType("int");

                    b.Property<int>("Questao3")
                        .HasColumnType("int");

                    b.Property<int>("Questao4")
                        .HasColumnType("int");

                    b.Property<int>("Questao5")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Visitantes");
                });
#pragma warning restore 612, 618
        }
    }
}
